### ISSUE TITLE
Current Event BGM Music Overlapping

### ISSUE THREAD

**Issue by LatidoReMe** [tangpei506/bangdream-data-viewer#3]
When you play the event bgm, it'll keep running on other parts of the site too. When you return to the Current Event page, you will not see the song playing, and can start it up again.

Playing the song twice causes two instances of the song, with them both at different parts.

You can actually do this as much as you please I think, as I was able to do it at least 10 times in a row. 

You can also still use the Music section while the bgm music is playing, and the bgm music won't loop if played from the Home page.

**Comment by tangpei506** [comment]
Could you please tell me the browser and its version you are using? And on which platform? Thanks.

**Comment by tangpei506** [comment]
Fixed
